stuff = list()
stuff.append('book')
stuff.append('pencil')
stuff.append('laptop')
stuff.append('tablet')
print(stuff)
print("NICE ONE BRUVA")
#Check it
print("I lost the ", stuff[2], ". We should sort this out.\n SORTING!")
stuff.sort()
print(stuff)
print("Great. That's done. Now let's check how many, what the highest, lowest, sum and average are.")
#print(len(stuff))
#print(max(stuff))
#print(min(stuff))
#print(sum(stuff))
#print(sum(stuff)/len(stuff))